var express = require('express');
var path = require('path');
var bodyParser = require('body-parser');
var mongo = require('mongoose');
var ObjectID = require('mongodb').ObjectID;
var sanitize = require('mongo-sanitize');

var db = mongo.connect('mongodb+srv://curvey:curveyrocks@cluster0.zh6u2.mongodb.net/CurveyDatabase?retryWrites=true&w=majority', function(err, response){
    if(err){
        console.log(err);
    }else{
        console.log('Connected to database'+ db, ' + ', response);
    }
});
// Start security code
const passport = require('passport');
require('./models/user.model');
require('./controllers/auth.controller');
const permissionController = require('./controllers/permission.controller');
const config = require('./env.config');
const Member = config.permissionLevels.Member;


// Load the REST service for users (generated by express generator)
var usersRouter = require('./routes/users');
// End security code

var app = express()
app.use(bodyParser());
app.use(bodyParser.json({limit:'5mb'}));
app.use(bodyParser.urlencoded({extended: true}));

var distDir = __dirname + "/dist/";
app.use(express.static(distDir));



app.use(function(req, res, next){
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
    res.setHeader('Access-Control-Allow-Credentials', true);
    next();
});
// Start security code
// Map the '/users' URI/URL to the users route. (routes/user.js)
app.use('/users', usersRouter);
// End security code

var Schema = mongo.Schema;

var SurveySchema = new Schema({
    _id: {type: ObjectID},
    title: {type: String},
    description: {type: String},
    questions: {type: Array}
}, {versionKey:false});

var model = mongo.model('survey', SurveySchema, 'survey');

app.post("/api/survey/create", function(req,res){
    var NewSchema = new Schema({
        title: {type: String},
        description: {type: String},
        questions: {type: Array}
    }, {versionKey:false});
    var newModel = mongo.model(req.body.title, NewSchema, 'survey');
    var newSurvey = new newModel(req.body);
    newSurvey.save(function(err, data){
        if(err){
            res.send(err)
        }else{
            res.send(data)
        }
    });
});

app.post("/api/survey/update", [passport.authenticate('jwt', {session: false}), permissionController.minimumPermissionLevelRequired(Member),function(req,res,next){
    req.body = sanitize(req.body);
    let id = req.body._id;
    delete req.body._id;
    model.findByIdAndUpdate(id, req.body, function(err, survey){
        if (err){
            return next(err);
        }
        res.status(200).send(survey);
    });
}]);

app.post("/api/survey/delete", [passport.authenticate('jwt', {session: false}), permissionController.minimumPermissionLevelRequired(Member), function(req,res){
    var survey = new model(req.body);
    survey.remove({_id: req.body.id}, function(err){
        if(err){
            res.send(err)
        }else{
            res.send({data:"Deleted succesfuly"})
        }
    });
}]);

app.get("/api/survey", function(req,res){
    model.find({}, function(err, data){
        if(err){
            res.send(err)
        }else{
            res.send(data)
        }
    });
});

app.get('*', (request, response) => {
	response.sendFile(path.join(__dirname, "/dist/", 'index.html'));
});


var server = app.listen(process.env.PORT || 3000, function () {
    var port = server.address().port;
    console.log("App now running on port", port);
  });
